server:
  port: 8080
spring:
  freemarker:
    template-loader-path: classpath:/templates/freemaker/
  redis:
    host: 47.100.237.222
    port: 6379
    database: 0
    timeout: 2000
  kafka:
    producer:
        bootstrap-servers: 47.100.237.222:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        retries: 0
        batch-size: 16384
        buffer-memory: 33554432
        properties:
          linger.ms: 1
    consumer:
        enable-auto-commit: false
        group-id: feature-forwarding
        #earliest #latest
        auto-offset-reset: earliest
        #kafka ip port
        bootstrap-servers: 47.100.237.222:9092
        auto-commit-interval: 100
        heartbeat-interval: 500
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        max-poll-records: 1000
    listener:
          # kafka消费者并发数
          concurrency: 20
logging:
  config: classpath:logback-spring.xml
eureka:
  client:
    service-url:
      defaultZone: http://47.100.237.222:8081/eureka/
